const cfg=window.JOBFINDER_CONFIG;
const sb=supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const el={auth:$("#auth"),app:$("#app"),email:$("#email"),password:$("#password"),msg:$("#auth-msg"),content:$("#content"),title:$("#title"),subtitle:$("#subtitle"),userEmail:$("#user-email"),modal:$("#modal"),modalBody:$("#modal-body"),toast:$("#toast")};

const demoJobs=[
{id:"d1",company_name:"Banca Generali",role_title:"AI Product Manager",location:"Milano",fit_score:9.6,priority:"APPLY",status:"NEW",source_url:"#"},
{id:"d2",company_name:"Generali",role_title:"Group CRM & Customer Engagement Senior Professional",location:"Milano",fit_score:9.5,priority:"APPLY",status:"REVIEW",source_url:"#"},
{id:"d3",company_name:"Lutech",role_title:"AI Strategy & Adoption Consultant",location:"Milano",fit_score:9.2,priority:"APPLY",status:"APPLY",source_url:"#"},
{id:"d4",company_name:"Harvey",role_title:"Enterprise Account Executive",location:"Milano",fit_score:9.0,priority:"APPLY",status:"APPLIED",source_url:"#"},
{id:"d5",company_name:"MotorK",role_title:"Customer Success Manager Automotive",location:"Milano",fit_score:8.8,priority:"REVIEW",status:"CONTACTED",source_url:"#"},
{id:"d6",company_name:"DAZN",role_title:"Senior Product Manager, Growth",location:"Milano",fit_score:8.7,priority:"APPLY",status:"INTERVIEW",source_url:"#"}];

let state={user:null,jobs:[],companies:[],followups:[],prefs:null,demo:false};

function toast(t){el.toast.textContent=t;el.toast.classList.remove("hidden");clearTimeout(window.__t);window.__t=setTimeout(()=>el.toast.classList.add("hidden"),2200)}
function esc(v=""){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}
function showApp(){el.auth.classList.add("hidden");el.app.classList.remove("hidden")}
function showAuth(){el.app.classList.add("hidden");el.auth.classList.remove("hidden")}
async function read(table){const {data,error}=await sb.from(table).select("*");if(error){console.warn(table,error.message);return []}return data||[]}
async function load(){const [jobs,companies,followups,prefs]=await Promise.all([read("jobs"),read("companies"),read("followups"),read("search_preferences")]);state.jobs=jobs.length?jobs:JSON.parse(JSON.stringify(demoJobs));state.demo=!jobs.length;state.companies=companies;state.followups=followups;state.prefs=prefs[0]||null}
function avg(){return state.jobs.length?state.jobs.reduce((a,j)=>a+Number(j.fit_score||0),0)/state.jobs.length:0}
function label(s){return ({NEW:"Nuova",REVIEW:"Review",APPLY:"Da applicare",APPLIED:"Application",CONTACTED:"Screening",INTERVIEW:"Colloquio",OFFER:"Offer",CLOSED:"Chiusa"}[s]||s)}
function jobHtml(j){return `<div class="job"><div><div class="job-title">${esc(j.role_title)}</div><div class="meta">${esc(j.company_name)} · ${esc(j.location||"")}</div><span class="pill">${esc(label(j.status))}</span></div><div class="fit">${Number(j.fit_score).toFixed(1)}/10<small>FIT</small></div><button class="apply" data-action="prepare" data-id="${esc(j.id)}">Applica ora</button><button class="save" data-action="save" data-id="${esc(j.id)}">♡</button></div>`}
function kpi(l,v){return `<div class="card kpi"><span>${l}</span><strong>${v}</strong></div>`}
function setPage(page){$$(".nav").forEach(b=>b.classList.toggle("active",b.dataset.page===page));const names={dashboard:"Ecco il tuo overview di oggi",opportunities:"Le migliori opportunità per te",pipeline:"Segui ogni candidatura",applications:"Tutte le candidature attive",companies:"Le aziende che vuoi monitorare",followups:"Non perdere il prossimo passo",feedback:"Allena le tue preferenze",preferences:"Configura la ricerca"};el.subtitle.textContent=names[page]||"";({dashboard,opportunities,pipeline,applications,companies,followups,feedback,preferences}[page]||dashboard)()}
function dashboard(){const top=[...state.jobs].sort((a,b)=>b.fit_score-a.fit_score).slice(0,5);el.content.innerHTML=`<div class="kpis">${kpi("OPPORTUNITÀ ALTO FIT",state.jobs.filter(j=>j.fit_score>=7).length)}${kpi("APPLICATION IN CORSO",state.jobs.filter(j=>["APPLIED","CONTACTED","INTERVIEW","OFFER"].includes(j.status)).length)}${kpi("COLLOQUI",state.jobs.filter(j=>j.status==="INTERVIEW").length)}${kpi("OFFERTE",state.jobs.filter(j=>j.status==="OFFER").length)}${kpi("AZIENDE TARGET",state.companies.length||12)}</div><div class="grid2"><section class="card panel"><div class="toolbar"><h2>Top opportunità per te</h2><button class="ghost" data-page-link="opportunities">Vedi tutte</button></div>${top.map(jobHtml).join("")}</section><section class="card panel"><h2>Prossime azioni</h2><div class="row"><span>Invia application per ${esc(top[0]?.role_title||"")}</span><span class="pill">ALTA PRIORITÀ</span></div><div class="row"><span>Follow-up recruiter</span><span class="pill">OGGI</span></div><div class="row"><span>Prepara colloquio</span><span class="pill">DOMANI</span></div></section></div>`}
function opportunities(){el.content.innerHTML=`<section class="card panel"><div class="toolbar"><h2>Opportunità</h2><button class="primary" data-action="new-job">+ Aggiungi</button></div>${state.jobs.sort((a,b)=>b.fit_score-a.fit_score).map(jobHtml).join("")}</section>`}
function pipeline(){const cols=[["Da valutare",["NEW","REVIEW","APPLY"]],["Application",["APPLIED"]],["Screening",["CONTACTED"]],["Colloqui / Offer",["INTERVIEW","OFFER"]]];el.content.innerHTML=`<div class="board">${cols.map(([n,ss])=>`<div class="col"><b>${n}</b>${state.jobs.filter(j=>ss.includes(j.status)).map(j=>`<div class="kanban"><b>${esc(j.role_title)}</b><p>${esc(j.company_name)}</p><button class="ghost" data-action="advance" data-id="${esc(j.id)}">Avanza →</button></div>`).join("")}</div>`).join("")}</div>`}
function applications(){const rows=state.jobs.filter(j=>["APPLIED","CONTACTED","INTERVIEW","OFFER"].includes(j.status));el.content.innerHTML=`<section class="card panel"><div class="toolbar"><h2>Le mie Application</h2><button class="primary" data-page-link="opportunities">+ Nuova application</button></div><table class="table"><tr><th>Azienda</th><th>Ruolo</th><th>Fit</th><th>Stato</th><th></th></tr>${rows.map(j=>`<tr><td>${esc(j.company_name)}</td><td>${esc(j.role_title)}</td><td>${Number(j.fit_score).toFixed(1)}</td><td>${esc(label(j.status))}</td><td><button class="ghost" data-action="prepare" data-id="${esc(j.id)}">Apri Copilot</button></td></tr>`).join("")}</table></section>`}
function companies(){const list=state.companies.length?state.companies:[{name:"Banca Generali",tier:"A"},{name:"Generali",tier:"A"},{name:"Deloitte",tier:"B"},{name:"EY",tier:"B"},{name:"Accenture",tier:"B"}];el.content.innerHTML=`<section class="card panel"><div class="toolbar"><h2>Aziende Target</h2><button class="primary" data-action="new-company">+ Aggiungi azienda</button></div>${list.map(c=>`<div class="row"><span><b>${esc(c.name)}</b><br><small class="muted">Tier ${esc(c.tier||"B")}</small></span><button class="ghost" data-action="open-company" data-name="${esc(c.name)}">Apri scheda</button></div>`).join("")}</section>`}
function followups(){el.content.innerHTML=`<section class="card panel"><div class="toolbar"><h2>Follow-up</h2><button class="primary" data-action="new-followup">+ Nuovo follow-up</button></div>${state.followups.length?state.followups.map(f=>`<div class="row"><span>${esc(f.action)}</span><span class="pill">${f.due_at?new Date(f.due_at).toLocaleDateString("it-IT"):"Da fare"}</span></div>`).join(""):`<div class="empty">Nessun follow-up salvato.</div>`}</section>`}
function feedback(){el.content.innerHTML=`<section class="card panel"><h2>Feedback</h2>${state.jobs.map(j=>`<div class="row"><span><b>${esc(j.role_title)}</b><br><small class="muted">${esc(j.company_name)}</small></span><span><button class="ghost" data-action="feedback" data-value="LIKE" data-id="${esc(j.id)}">👍</button> <button class="ghost" data-action="feedback" data-value="PASS" data-id="${esc(j.id)}">PASS</button> <button class="ghost" data-action="feedback" data-value="DISLIKE" data-id="${esc(j.id)}">👎</button></span></div>`).join("")}</section>`}
function preferences(){const p=state.prefs||{};el.content.innerHTML=`<section class="card panel"><h2>Preferenze</h2><div class="form"><div><label>Ruoli target</label><textarea id="roles" rows="5">${esc((p.role_tags||["Customer Experience","Business Strategy","Sales Ops / RevOps","AI Strategy","AI Product"]).join(", "))}</textarea></div><div><label>Settori</label><textarea id="industries" rows="5">${esc((p.industry_tags||["Tech","AI","Automotive","Motorsport","Gaming"]).join(", "))}</textarea></div><div><label>Località</label><input id="locations" value="${esc((p.location_tags||["Milano","Remote Italy","EU"]).join(", "))}"></div><div><label>Fit minimo</label><input id="minfit" type="number" value="${Number(p.min_fit||7)}"></div><div class="full"><button class="primary" data-action="save-prefs">Salva preferenze</button></div></div></section>`}
function openModal(html){el.modalBody.innerHTML=html;el.modal.classList.remove("hidden")}
function closeModal(){el.modal.classList.add("hidden")}
function findJob(id){return state.jobs.find(j=>String(j.id)===String(id))}
function prepare(id){const j=findJob(id);if(!j)return;openModal(`<h2>✨ Application Copilot</h2><p>${esc(j.company_name)} · ${esc(j.role_title)}</p><div class="form"><div><label>CV consigliato</label><select id="cv"><option>AI / Strategy</option><option>CX / Customer Success</option><option>Commercial / Enterprise</option><option>Automotive</option></select></div><div><label>Stato</label><select id="app-status"><option>PREPARING</option><option>READY</option><option>SUBMITTED</option></select></div><div class="full"><label>Nota recruiter</label><textarea id="note" rows="4"></textarea></div><div class="full"><button class="primary" data-action="confirm-application" data-id="${esc(j.id)}">Prepara application</button></div></div>`)}
async function confirmApplication(id){const j=findJob(id);if(!j)return;if(state.demo){j.status="APPLIED";closeModal();toast("Application preparata");applications();return}const {error}=await sb.from("applications").upsert({user_id:state.user.id,job_id:j.id,status:$("#app-status").value,cv_variant:$("#cv").value,notes:$("#note").value||null},{onConflict:"user_id,job_id"});if(error)return toast("Errore: "+error.message);await sb.from("jobs").update({status:"APPLIED"}).eq("id",j.id).eq("user_id",state.user.id);await load();closeModal();toast("Application preparata");applications()}
async function advance(id){const j=findJob(id);if(!j)return;const order=["NEW","REVIEW","APPLY","APPLIED","CONTACTED","INTERVIEW","OFFER","CLOSED"];const ix=Math.max(0,order.indexOf(j.status));j.status=order[Math.min(ix+1,order.length-1)];if(!state.demo){const {error}=await sb.from("jobs").update({status:j.status}).eq("id",j.id).eq("user_id",state.user.id);if(error)return toast(error.message)}toast("Stato aggiornato");pipeline()}
async function sendFeedback(id,value){if(state.demo)return toast("Feedback registrato");const {error}=await sb.from("feedback").insert({user_id:state.user.id,job_id:id,signal:value,reasons:[]});toast(error?"Errore: "+error.message:"Feedback salvato")}
async function savePrefs(){const payload={user_id:state.user.id,role_tags:$("#roles").value.split(",").map(x=>x.trim()).filter(Boolean),industry_tags:$("#industries").value.split(",").map(x=>x.trim()).filter(Boolean),location_tags:$("#locations").value.split(",").map(x=>x.trim()).filter(Boolean),work_mode_tags:["Hybrid","Remote"],min_fit:Number($("#minfit").value||7),ai_learning_enabled:true};const {error}=await sb.from("search_preferences").upsert(payload,{onConflict:"user_id"});if(error){localStorage.setItem("jobfinder_prefs",JSON.stringify(payload));toast("Salvate localmente")}else{state.prefs=payload;toast("Preferenze salvate")}}
function newCompany(){openModal(`<h2>Nuova azienda target</h2><div class="form"><div class="full"><input id="co-name" placeholder="Nome azienda"></div><div><select id="co-tier"><option>A</option><option>B</option><option>C</option></select></div><div><input id="co-sector" placeholder="Settore"></div><div class="full"><button class="primary" data-action="save-company">Salva</button></div></div>`)}
async function saveCompany(){const name=$("#co-name").value.trim();if(!name)return toast("Inserisci il nome");if(state.demo){state.companies.push({name,tier:$("#co-tier").value});closeModal();companies();return}const {error}=await sb.from("companies").insert({user_id:state.user.id,name,tier:$("#co-tier").value,sector:$("#co-sector").value||null});if(error)return toast(error.message);await load();closeModal();companies()}
function newFollowup(){openModal(`<h2>Nuovo follow-up</h2><div class="form"><div class="full"><input id="fu-action" placeholder="Es. Scrivere al recruiter"></div><div class="full"><input id="fu-date" type="datetime-local"></div><div class="full"><button class="primary" data-action="save-followup">Salva</button></div></div>`)}
async function saveFollowup(){const action=$("#fu-action").value.trim();if(!action)return toast("Inserisci l'azione");if(state.demo){state.followups.push({action,due_at:$("#fu-date").value});closeModal();followups();return}const {error}=await sb.from("followups").insert({user_id:state.user.id,action,due_at:$("#fu-date").value||null});if(error)return toast(error.message);await load();closeModal();followups()}

document.addEventListener("click",async e=>{
 const btn=e.target.closest("button");if(!btn)return;
 if(btn.dataset.page){setPage(btn.dataset.page);return}
 if(btn.dataset.pageLink){setPage(btn.dataset.pageLink);return}
 const a=btn.dataset.action;
 if(a==="prepare")return prepare(btn.dataset.id);
 if(a==="save"){btn.textContent=btn.textContent==="♥"?"♡":"♥";return toast(btn.textContent==="♥"?"Salvata":"Rimossa")}
 if(a==="advance")return advance(btn.dataset.id);
 if(a==="confirm-application")return confirmApplication(btn.dataset.id);
 if(a==="feedback")return sendFeedback(btn.dataset.id,btn.dataset.value);
 if(a==="save-prefs")return savePrefs();
 if(a==="new-company")return newCompany();
 if(a==="save-company")return saveCompany();
 if(a==="new-followup")return newFollowup();
 if(a==="save-followup")return saveFollowup();
 if(a==="open-company")return openModal(`<h2>${esc(btn.dataset.name)}</h2><p class="muted">Scheda azienda target pronta per note, contatti e opportunità.</p>`);
 if(a==="new-job")return toast("Aggiunta opportunità: prossimo step");
});
$("#close-modal").onclick=closeModal;el.modal.addEventListener("click",e=>{if(e.target===el.modal)closeModal()});
$("#login").onclick=async()=>{el.msg.textContent="";const email=el.email.value.trim(),password=el.password.value;if(!email||!password){el.msg.textContent="Inserisci email e password.";return}const {data,error}=await sb.auth.signInWithPassword({email,password});if(error){el.msg.textContent="Email o password non corretti.";return}if(data.user)boot(data.user)};
$("#forgot").onclick=async()=>{const email=el.email.value.trim();if(!email){el.msg.textContent="Inserisci prima l'email.";return}const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:cfg.appUrl});el.msg.textContent=error?error.message:"Controlla la tua email per reimpostare la password."};
$("#logout").onclick=async()=>{await sb.auth.signOut();state.user=null;showAuth()};
async function boot(user){state.user=user;el.userEmail.textContent=user.email||"";showApp();await load();el.title.textContent="Bentornata! 👋";setPage("dashboard")}
sb.auth.onAuthStateChange((event,session)=>{if(session?.user&&!state.user)boot(session.user);if(!session?.user&&state.user){state.user=null;showAuth()}});
(async()=>{const {data:{session}}=await sb.auth.getSession();if(session?.user)boot(session.user);else showAuth()})();
